### ISSUE TITLE
Help needed in understanding the eclipse che dependency in docker Image

### ISSUE THREAD

**Issue by fahimkhan** [eclipse/che-dockerfiles#245]
Hi,

I have taken the image from "FROM eclipse/ubuntu_jdk8" which has all the dependency required to create and run the eclipse che workspace. The normal size of image is around 500MB. However, the size of image is getting in GB's after adding other packages. 

I am actually looking for minimum ubuntu image with eclipse che dependency. So that we can allocate minimum RAM to each workspace created in the eclipse che.

Is there any minimum ubuntu image with eclipse che dependency. or Can you please let me know what all dependency I should install in any Ubuntu image to make it run the eclipse che workspace.

Thanks.

**Comment by AndrienkoAleksandr** [comment]
Hello @fahimkhan  on the latest Eclipse CHE, actually you can use any image with endless `ENTRYPOINT`  or `CMD` command. I mean container entrypoint process could be some endless command for example tomcat, some binary, endless script. If you don't have endless entrypoint command you can apply some synthetic one https://github.com/eclipse/che-dockerfiles/blob/master/recipes/ubuntu_go/Dockerfile#L53 .
Eclipse CHE stops workspace if some container stopped, that's why you need to use such entry points.

 And if you want to have image which could be launched on the openshift read this article: 
https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html

> INFO:  in the nearest feature for Eclipse CHE  base images we want to use UBI: https://www.redhat.com/en/blog/introducing-red-hat-universal-base-image

> WARNING for quite old version Eclipse CHE we had conception dev-machine and workspace-agent. For such old version Eclipse CHE you need java for dev machine container. But I think it's better to use never Eclipse CHE version.

**Comment by fahimkhan** [comment]
Thanks @AndrienkoAleksandr . Does it mean that there are not any dependency package require inside my custom image.
I will also check with endless entry point.
